Make sure music is not paused if music is not playing - Troubleshooting
Repulser/RythmFAQ pull request #27
Opened 2017-10-31 06:36 UTC by BrandonKoala

Recently had an issue where a user couldn't hear any audio, after quite a while I joined the server to find that the song had been paused. Figured it would be a good idea to add it to the Troubleshooting guide.

2017-10-31 07:15 UTC, Repulser requested changes
I would prefer the usage of `!resume` here as its clearer.

2017-10-31 08:43 UTC, BrandonKoala commented
Fixed.

2017-10-31 08:46 UTC, Repulser approved these changes

2017-11-01 11:00 UTC, craziii commented
Can you swap the code and bold tags? Cos that keeps with the formatting we already have for commands

2017-11-01 14:27 UTC, merged